### ISSUE TITLE
Help on compilation

### ISSUE THREAD

**Issue by s-hoviegar** [springframeworkguru/spring-boot-rabbitmq-example#5]
Hi there!
I tried to compile this project in IntelliJ Idea 2020.2.3 and got this error:
`Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project spring-boot-rabbitmq: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test failed: Cannot invoke "org.apache.maven.surefire.shade.org.apache.commons.lang3.JavaVersion.atLeast(org.apache.maven.surefire.shade.org.apache.commons.lang3.JavaVersion)" because "org.apache.maven.surefire.shade.org.apache.commons.lang3.SystemUtils.JAVA_SPECIFICATION_VERSION_AS_ENUM" is null`
Could you pleas help me to resolve this problem? After all thanks for this great project and keep up the good work.
Thanks in advanced...

**Comment by s-hoviegar** [comment]
I managed to be able to up and running this project with docker with the following steps.

1. git clone https://github.com/springframeworkguru/spring-boot-rabbitmq-example.git

2. edit pom.xml in the <plugins> section adding:
	
```
	<executions>
        <execution>
			<goals>
				<goal>repackage</goal>
            </goals>
        </execution>
    </executions>
```
	
3. edit src/main/resources/application.properties
	
```
	# ===============================
	# = DATA SOURCE
	# ===============================
	# Set here configurations for the database connection
	spring.datasource.url=jdbc:mysql://db:3306/springboot_rabbitmq_example
	spring.datasource.username=user
	spring.datasource.password=password
	spring.datasource.driver-class-name=com.mysql.jdbc.Driver
	# Keep the connection alive if idle for a long time (needed in production)
	spring.datasource.testWhileIdle=true
	spring.datasource.validationQuery=SELECT 1

	spring.rabbitmq.host = rabbitmq-cont
	spring.rabbitmq.port = 5672
	spring.rabbitmq.username = guest
	spring.rabbitmq.password = guest

	# ===============================
	# = JPA / HIBERNATE
	# ===============================
	# Show or not log for each sql query
	spring.jpa.show-sql=true
	# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
	# schema will be automatically created afresh for every start of application
	spring.jpa.hibernate.ddl-auto=create-drop
	# Naming strategy
	spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
	# Allows Hibernate to generate SQL optimized for a particular DBMS
	spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
```
	
4. create Dockerfile
	
```
	######## build stage ########
	FROM maven:3.6.3-openjdk-8 as maven_build

	WORKDIR /app
	COPY ./spring-boot-rabbitmq-example/ ./
	RUN mvn package -DskipTests

	#COPY pom.xml .
	# To resolve dependencies in a safe way (no re-download when the source code changes)
	#RUN mvn clean package -Dmaven.main.skip -Dmaven.test.skip && rm -r target

	# To package the application
	#COPY src ./src
	#RUN mvn clean package -Dmaven.test.skip

	######## run stage ########
	FROM java:8

	WORKDIR /app
	COPY --from=maven_build /app/target/*.jar ./

	# Git clone wait for script
	RUN git clone https://github.com/vishnubob/wait-for-it.git

	#run the app
	ENV JAVA_OPTS ""
	CMD ["./wait-for-it/wait-for-it.sh", "rabbitmq-cont:15672", "--", "bash", "-c", "java ${JAVA_OPTS} -jar *.jar -v"]
```
	
5. docker build -t hoviegar/spring-boot-rabbitmq-example .
	
6. create docker-compose.yml

```
version: "3"
	services:
        rabbitmq-cont:
                image: rabbitmq:management
                restart: always
                ports:
					- "15672:15672"
        db:
                image: mysql:5.7
                restart: always
                environment:
					MYSQL_DATABASE: 'springboot_rabbitmq_example'
					# So you don't have to use root, but you can if you like
					MYSQL_USER: 'user'
					# You can use whatever password you like
					MYSQL_PASSWORD: 'password'
					# Password for root access
					MYSQL_ROOT_PASSWORD: 'my-secret-pw'
                ports:
					# <Port exposed> : < MySQL Port running inside container>
					- '3306:3306'
                expose:
					# Opens port 3306 on the container
					- '3306'
                volumes:
					# Where our data will be persisted
					- my-db:/var/lib/mysql
        application:
			image: hoviegar/spring-boot-rabbitmq-example
			depends_on:
				- rabbitmq-cont
				- db
			ports:
				- "8080:8080"
	# Names our volume
	volumes:
        my-db:
```
		
7. docker-compose up

8. visit http://localhost:8080/ for application and http://localhost:15672 for rabbitmq

I uploaded hoviegar/spring-boot-rabbitmq-example image to docker hub so no need to create the docker image in steps 4 and 5 if you don't want. But if you want to create a local image be sure to edit image option in docker-compose.yml file.
 
```
	#COPY pom.xml .
	# To resolve dependencies in a safe way (no re-download when the source code changes)
	#RUN mvn clean package -Dmaven.main.skip -Dmaven.test.skip && rm -r target

	# To package the application
	#COPY src ./src
	#RUN mvn clean package -Dmaven.test.skip
```
 
The above lines are commented out in Dockerfile because I couldn't find a way to compile the project in that way. The reason I wanted these lines instead of a simple mvn package was that the Dockerfile be in a way that downloads dependencies just one time and cache the process and if the source code changes there will be no need to download the whole dependencies again. I would really appreciate it if anybody could help me do this step in a better way...
By the way thanks for sharing the project.
